/**
 * Plugin System Types
 * Core type definitions for the Scaforge plugin system
 */
import { z } from 'zod';

/**
 * Plugin categories for grouping plugins in the CLI
 */
export type PluginCategory =
  | 'api'
  | 'cms'
  | 'auth'
  | 'database'
  | 'payments'
  | 'email'
  | 'storage'
  | 'analytics'
  | 'monitoring'
  | 'caching'
  | 'jobs'
  | 'search'
  | 'flags'
  | 'sms'
  | 'push'
  | 'realtime'
  | 'ai'
  | 'vector'
  | 'i18n'
  | 'forms'
  | 'state'
  | 'testing'
  | 'security'
  | 'media'
  | 'maps'
  | 'charts'
  | 'pdf'
  | 'seo'
  | 'scheduling'
  | 'comments'
  | 'notifications'
  | 'admin'
  | 'content'
  | 'indonesian';

/**
 * Supported framework templates
 */
export type FrameworkTemplate = 'nextjs' | 'tanstack' | 'nuxt' | 'hydrogen';

/**
 * Environment variable definition for plugins
 */
export interface EnvVarDefinition {
  /** Environment variable name */
  name: string;
  /** Description of what this variable is for */
  description: string;
  /** Whether this variable is required */
  required: boolean;
  /** Default value if not provided */
  default?: string;
  /** Whether this is a secret value */
  secret?: boolean;
}


/**
 * Condition for file generation
 */
export interface FileCondition {
  /** Plugin that must be installed */
  hasPlugin?: string;
  /** Plugin that must NOT be installed */
  notHasPlugin?: string;
  /** Template that must be used */
  template?: FrameworkTemplate;
  /** Custom condition function name */
  custom?: string;
}

/**
 * File to be generated by a plugin
 */
export interface PluginFile {
  /** Target path relative to project root */
  path: string;
  /** Template content or path to template file */
  template: string;
  /** Conditions for generating this file */
  condition?: FileCondition;
  /** Whether to overwrite existing file */
  overwrite?: boolean;
}

/**
 * Integration type for plugin-to-plugin integrations
 */
export type IntegrationType = 'middleware' | 'provider' | 'hook' | 'config';

/**
 * Plugin integration definition
 */
export interface PluginIntegration {
  /** Plugin to integrate with */
  plugin: string;
  /** Integration type */
  type: IntegrationType;
  /** Files to generate for this integration */
  files: PluginFile[];
}

/**
 * NPM packages required by a plugin
 */
export interface PluginPackages {
  /** Production dependencies */
  dependencies?: Record<string, string>;
  /** Development dependencies */
  devDependencies?: Record<string, string>;
}

/**
 * Complete plugin definition
 */
export interface PluginDefinition {
  /** Unique plugin identifier (e.g., 'api-trpc', 'auth-clerk') */
  name: string;
  
  /** Human-readable display name */
  displayName: string;
  
  /** Plugin category for grouping */
  category: PluginCategory;
  
  /** Short description */
  description: string;
  
  /** Plugin version */
  version: string;
  
  /** Supported framework templates */
  supportedTemplates: FrameworkTemplate[];
  
  /** Dependencies on other plugins */
  dependencies?: string[];
  
  /** Plugins that conflict with this one */
  conflicts?: string[];
  
  /** NPM packages to install */
  packages: PluginPackages;
  
  /** Configuration schema using Zod */
  configSchema?: z.ZodType;
  
  /** Environment variables required */
  envVars?: EnvVarDefinition[];
  
  /** Files to generate */
  files: PluginFile[];
  
  /** Integration hooks with other plugins */
  integrations?: PluginIntegration[];
  
  /** Post-install instructions shown to user */
  postInstall?: string;
}

/**
 * Helper function to define a plugin with type safety
 */
export function definePlugin(definition: PluginDefinition): PluginDefinition {
  return definition;
}
